version: 0.2

env:
  parameter-store:
     DOCKER_REGISTRY_USERNAME: "/springboot-application/docker-credentials/username"
     DOCKER_REGISTRY_PASSWORD: "/springboot-application/docker-credentials/password"
     DOCKER_REGISTRY_URL: "/springboot-application/docker-credentials/docker-URL"
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  install:
    runtime-versions:
      python: 3.11
    #commands:
      # - command
      # - command
  pre_build:
    commands:
       - pip install -r requirement.txt
      
  build:
    commands:
      - echo "Building Docker Images"
      - docker login -u "$DOCKER_REGISTRY_USERNAME" -p "$DOCKER_REGISTRY_PASSWORD"
      - docker build -t springboot-application .
      - docker tag springboot-application "$DOCKER_REGISTRY_USERNAME/springboot-application:latest"
      - docker push "$DOCKER_REGISTRY_USERNAME/springboot-application:latest"
  post_build:
    commands:
      - echo "Docker image is Created and Pushed Successfully"
      # - command
